#!/bin/bash
set -e

MODE=${1:-gateway}

if [ "$MODE" = "dashboard" ]; then
  echo "Starting Huginn Dashboard..."
  /opt/hermes/.venv/bin/python -m mnemosyne.install
  exec /opt/hermes/.venv/bin/hermes dashboard --host 0.0.0.0 --insecure
else
  echo "Starting Huginn Gateway..."

  # Ensure HOME is correctly set to the persistent data volume.
  # This ensures files generated by git, gh, and ssh persist across container restarts,
  # and prevents them from ending up in /root due to Docker/s6-overlay environment leakage.
  export HOME=/opt/data/home

  # 1. Setup SSH directory and keys natively in the persistent home directory
  mkdir -p "$HOME/.ssh" && chmod 700 "$HOME/.ssh"
  if [ -f /run/secrets/hermes_ssh_key ]; then
    echo "Configuring SSH key..."
    tr -d "\r" < /run/secrets/hermes_ssh_key > "$HOME/.ssh/id_rsa"
    echo "" >> "$HOME/.ssh/id_rsa"
    chmod 600 "$HOME/.ssh/id_rsa"
    ssh-keyscan github.com > "$HOME/.ssh/known_hosts" 2>/dev/null
    chmod 600 "$HOME/.ssh/known_hosts"
  fi

  # 2. Configure GitHub CLI (gh) credentials
  if [ -n "${GH_SETUP_TOKEN}" ]; then
    echo "Logging in to GitHub CLI..."
    if echo "${GH_SETUP_TOKEN}" | gh auth login --with-token; then
      echo "GitHub CLI login successful."
    else
      echo "Warning: GitHub CLI authentication failed."
    fi
  fi

  # 3. Configure Git user name/email and safe directory
  git config --global user.name "${GIT_USER_NAME}"
  git config --global user.email "${GIT_USER_EMAIL}"
  git config --global safe.directory /app/vault

  # 4. Remove secret tokens from the process environment
  unset GH_SETUP_TOKEN
  unset GH_TOKEN
  unset GITHUB_TOKEN

  # 5. Initialize Mnemosyne and run the Hermes Agent gateway
  /opt/hermes/.venv/bin/python -m mnemosyne.install
  exec /opt/hermes/.venv/bin/hermes gateway run
fi
